### ISSUE TITLE
something confusing about transform

### ISSUE THREAD

**Issue by Bozenton** [bit-bots/bitbots_motion#362]
https://github.com/bit-bots/bitbots_motion/blob/9c67df43febb1da63dc9a7ac42a94d3d54b3953c/bitbots_quintic_walk/src/walk_engine.cpp#L454

Hi there,
As far as I know, the transform related to velocity is usually in the form like ${}^B V_Q = {}^B_A R {}^A V_Q$, where ${}^B_A R$ is the rotation matrix. 
Thus I think here is should be `trunk_pos_vel_at_foot_change_ = rotation_to_next.inverse() * trunk_pos_vel;` instead of `trunk_pos_vel_at_foot_change_ = rotation_to_next * trunk_pos_vel;`
Is that right? Hope for your help.

**Comment by SammyRamone** [comment]
Sorry for the late reply I kind of forgot about this issue until today.
You are correct, this should be the inverse. The same for the other velocities and accelerations.
I probably never realized the issue because this rotation is typically rather small and therefore the effect is not so big. Still, good to fix this.
Thanks for finding the bug :slightly_smiling_face: 

Here the movement of the feet before fixing the bug (while turning with a high speed to make the bug especially bad). There is a small bump during the foot exchange (e.g at 1.1s)
![Screenshot from 2022-11-09 16-33-47](https://user-images.githubusercontent.com/11520148/200874962-2185b3f0-4c82-449b-a3b2-390337c0d0a3.png)

After fixing the bug 
![Screenshot from 2022-11-09 16-38-41](https://user-images.githubusercontent.com/11520148/200874894-19f854e5-d0d5-4887-bcf5-7f1f0e9b4f0f.png)
