### ISSUE TITLE
If there is any method to make the robot walk in a straight line?

### ISSUE THREAD

**Issue by Bozenton** [bit-bots/bitbots_motion#404]
## What I'm trying to do

Hello, thanks for your sharing. We are applying your repo in our robot. But recently we found that the robot cannot walk in a straight line, for example we are using topic `cmd_vel` to control the robot: 

https://github.com/bit-bots/bitbots_motion/blob/040bacd51bf8cb995d471bb8451fa1d8cff54723/bitbots_quintic_walk/src/walk_node.cpp#L103-L106

we set the x of the twist as 0.1, others as 0, but the robot cannot go straight forward and it will deviate to the right or to the left. What's more, if we want it to rotate in its place, it would still have some x/y velocity.

## What I've tried

We have tried to add some static bias in the topic of `cmd_vel`, but it cannot solve the problem. We also tried to tune the parameters in the files in `bitbots_quintic_walk/config`, but we did not find the appropriate param for this problem. 

## Additional context

By the way, we are using your ROS1 version. 

Thanks for your attention and hope for your reply.

**Comment by Flova** [comment]
This may be a parameter issue, or it might be related to the hardware (e.g. one leg has more backlash or is less stiff). 
Does the robot model walk correctly forward in simulation? 
Do multiple identical robots have the same bias? 

We also had issues with this in the past. Some drift can be expected when the robot navigates in an open loop fashion, but in some cases it was quite extreme. One thing that helped us was a proper PID parameter tuning for the individual actuators. Some of them (e.g. the knees) need vastly different values. By doing this, the executed trajectories are much closer to the expected trajectories. 
In addition to that, the biases seemed to be very robot specific, so we worked on our hardware. Swapping actuators and structurally reducing the flex of the legs (more metal parts instead of 3D prints) helps significantly. The rest drift can be accounted for during navigation using visual feedback in the localization. 

For troubleshooting, I recommend plotting and comparing the motor commands and joint states of all major joints using plotjuggler. In addition to that, you can tweak the walk engine parameters. Seemingly unrelated things like foot rise etc. can influence this. Especially if the robot fails to follow the trajectory. Try to record slow motion videos of the walking gate and see if it looks as expected. Things like a non-level foot during ground contact can be something to look out for.
